import type { Metadata } from "next";
import { Geist_Mono, Sofia_Sans } from "next/font/google";
import "./globals.css";
import { ModeToggle } from "@/components/ModeToggle";
import { Toaster } from "@/components/ui/sonner"
import AppProvider from "@/components/providers/AppProvider";

const sans = Sofia_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

const serif = Geist_Mono({
  variable: "--font-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  authModal 
}: Readonly<{
  children: React.ReactNode;
  authModal : React.ReactNode,
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      
        <body
          className={`${sans.variable} ${serif.variable} font-sans antialiased`}
        >
          <AppProvider>
         
            
       
          
            {authModal}
            <main> {children}</main>
           
            <Toaster />
            <div className="fixed bottom-4 right-4">
              <ModeToggle />
            </div>
          </AppProvider>
          
        </body>
        

      
    </html>
  );
}
